### ISSUE TITLE
Error thrown when calling Storyhooks.generate()

### ISSUE THREAD

**Issue by MistakingManx** [thomascgray/fantasy-content-generator#20]
When calling fcg.Storyhooks.generate(), the following error is thrown.
Am I missing something?
`TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))`

Stack:
 ```
   at Function.from (<anonymous>)
    at Object.exports.pickMany (fantasy-content-generator\dist\utils\index.js:24:27)
    at Object.exports.pick (fantasy-content-generator\dist\utils\index.js:14:20)
    at fantasy-content-generator\dist\storyhooks\index.js:25:50
    at Object.exports.withSeed (fantasy-content-generator\dist\utils\index.js:153:23)
    at Object.generate (fantasy-content-generator\dist\storyhooks\index.js:22:18)
```

**Comment by thomascgray** [comment]
Huge apologise in the delay in getting back to you! This should now be fixed as of v4.9.0

Closing the issue.
